# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: manuela1215
# "service" is the name of this project. This will also be added to your AWS resource names.
service: tree-project

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  tree:
    handler: handler.tree
    events:
      - http:
          path: /tree
          method: get